title: Ruben Branco
url: "https://rubenbranco.github.io"
baseurl: "./"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

favicon: true
favicon_location: favicon.ico

footer: no
footer_url: "https://github.com/RubenBranco"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "./"
 - name: "CV"
   link: "https://drive.google.com/file/d/1IkYwV90qBOrX6z_5EVxYhzMBOBnBBZLO/view"